var dataList=[
    {
        checkoption:ko.observableArray([]),
        id:1,
        questionname:'我对公司未来的发展前景有信心',
        questiontype:0,
        option:[
            {
                id:11,
                optionname:'强烈不同意'
            },
            {
                id:12,
                optionname:'不同意'
            },
            {
                id:13,
                optionname:'基本不同意'
            },
            {
                id:14,
                optionname:'基本同意'
            },
            {
                id:15,
                optionname:'强烈同意'
            }
        ]
    },
    {
        checkoption:ko.observableArray([]),
        id:2,
        questionname:'我对公司未来的发展前景有信心',
        questiontype:0,
        option:[
            {
                id:21,
                optionname:'强烈不同意'
            },
            {
                id:22,
                optionname:'不同意'
            },
            {
                id:23,
                optionname:'基本不同意'
            },
            {
                id:24,
                optionname:'基本同意'
            },
            {
                id:25,
                optionname:'强烈同意'
            }
        ]
    },
    {
        checkoption:ko.observableArray([]),
        id:3,
        questionname:'在公司，创新的行为受到表彰和奖励。',
        questiontype:1,
        departments:[
            {
                departmentsid:1,
                departmentstitle:'部门一',
                questions:[
                    {
                        checkoption:ko.observableArray([]),
                        id:11,
                        title:'非常喜欢休息',
                        option:[
                            {
                                id:111,
                                value:1
                            },
                            {
                                id:112,
                                value:2
                            },
                            {
                                id:113,
                                value:3
                            },
                            {
                                id:114,
                                value:4
                            },
                            {
                                id:115,
                                value:5
                            }
                        ]
                    },
                    {
                        checkoption:ko.observableArray([]),
                        id:12,
                        title:'非常不喜欢工作',
                        option:[
                            {
                                id:121,
                                value:1
                            },
                            {
                                id:122,
                                value:2
                            },
                            {
                                id:123,
                                value:3
                            },
                            {
                                id:124,
                                value:4
                            },
                            {
                                id:125,
                                value:5
                            }
                        ]
                    },
                    {
                        checkoption:ko.observableArray([]),
                        id:13,
                        title:'非常满意工作',
                        option:[
                            {
                                id:131,
                                value:1
                            },
                            {
                                id:132,
                                value:2
                            },
                            {
                                id:133,
                                value:3
                            },
                            {
                                id:134,
                                value:4
                            },
                            {
                                id:135,
                                value:5
                            }
                        ]
                    },
                    {
                        checkoption:ko.observableArray([]),
                        id:14,
                        title:'非常想加班',
                        option:[
                            {
                                id:141,
                                value:1
                            },
                            {
                                id:142,
                                value:2
                            },
                            {
                                id:143,
                                value:3
                            },
                            {
                                id:144,
                                value:4
                            },
                            {
                                id:145,
                                value:5
                            }
                        ]
                    },
                    {
                        checkoption:ko.observableArray([]),
                        id:15,
                        title:'热爱公司文化',
                        option:[
                            {
                                id:151,
                                value:1
                            },
                            {
                                id:152,
                                value:2
                            },
                            {
                                id:153,
                                value:3
                            },
                            {
                                id:154,
                                value:4
                            },
                            {
                                id:155,
                                value:5
                            }
                        ]
                    },
                    {
                        checkoption:ko.observableArray([]),
                        id:16,
                        title:'热爱自己的工作',
                        option:[
                            {
                                id:161,
                                value:1
                            },
                            {
                                id:162,
                                value:2
                            },
                            {
                                id:163,
                                value:3
                            },
                            {
                                id:164,
                                value:4
                            },
                            {
                                id:165,
                                value:5
                            }
                        ]
                    },
                    {
                        checkoption:ko.observableArray([]),
                        id:17,
                        title:'非常不喜欢加班',
                        option:[
                            {
                                id:171,
                                value:1
                            },
                            {
                                id:172,
                                value:2
                            },
                            {
                                id:173,
                                value:3
                            },
                            {
                                id:174,
                                value:4
                            },
                            {
                                id:175,
                                value:5
                            }
                        ]
                    },
                    {
                        checkoption:ko.observableArray([]),
                        id:18,
                        title:'非常满意薪酬',
                        option:[
                            {
                                id:181,
                                value:1
                            },
                            {
                                id:182,
                                value:2
                            },
                            {
                                id:183,
                                value:3
                            },
                            {
                                id:184,
                                value:4
                            },
                            {
                                id:185,
                                value:5
                            }
                        ]
                    },
                    {
                        checkoption:ko.observableArray([]),
                        id:19,
                        title:'非常满意公司环境',
                        option:[
                            {
                                id:191,
                                value:1
                            },
                            {
                                id:192,
                                value:2
                            },
                            {
                                id:193,
                                value:3
                            },
                            {
                                id:194,
                                value:4
                            },
                            {
                                id:195,
                                value:5
                            }
                        ]
                    },
                    {
                        checkoption:ko.observableArray([]),
                        id:20,
                        title:'非常不喜欢公司氛围',
                        option:[
                            {
                                id:201,
                                value:1
                            },
                            {
                                id:202,
                                value:2
                            },
                            {
                                id:203,
                                value:3
                            },
                            {
                                id:204,
                                value:4
                            },
                            {
                                id:205,
                                value:5
                            }
                        ]
                    }
                ]
            },
            {
                departmentsid:2,
                departmentstitle:'部门一',
                questions:[
                    {
                        id:11,
                        title:'非常喜欢休息',
                        option:[
                            {
                                id:111,
                                value:1
                            },
                            {
                                id:112,
                                value:2
                            },
                            {
                                id:113,
                                value:3
                            },
                            {
                                id:114,
                                value:4
                            },
                            {
                                id:115,
                                value:5
                            }
                        ]
                    },
                    {
                        id:12,
                        title:'非常不喜欢工作',
                        option:[
                            {
                                id:121,
                                value:1
                            },
                            {
                                id:122,
                                value:2
                            },
                            {
                                id:123,
                                value:3
                            },
                            {
                                id:124,
                                value:4
                            },
                            {
                                id:125,
                                value:5
                            }
                        ]
                    },
                    {
                        id:13,
                        title:'非常满意工作',
                        option:[
                            {
                                id:131,
                                value:1
                            },
                            {
                                id:132,
                                value:2
                            },
                            {
                                id:133,
                                value:3
                            },
                            {
                                id:134,
                                value:4
                            },
                            {
                                id:135,
                                value:5
                            }
                        ]
                    },
                    {
                        id:14,
                        title:'非常想加班',
                        option:[
                            {
                                id:141,
                                value:1
                            },
                            {
                                id:142,
                                value:2
                            },
                            {
                                id:143,
                                value:3
                            },
                            {
                                id:144,
                                value:4
                            },
                            {
                                id:145,
                                value:5
                            }
                        ]
                    },
                    {
                        id:15,
                        title:'热爱公司文化',
                        option:[
                            {
                                id:151,
                                value:1
                            },
                            {
                                id:152,
                                value:2
                            },
                            {
                                id:153,
                                value:3
                            },
                            {
                                id:154,
                                value:4
                            },
                            {
                                id:155,
                                value:5
                            }
                        ]
                    },
                    {
                        id:16,
                        title:'热爱自己的工作',
                        option:[
                            {
                                id:161,
                                value:1
                            },
                            {
                                id:162,
                                value:2
                            },
                            {
                                id:163,
                                value:3
                            },
                            {
                                id:164,
                                value:4
                            },
                            {
                                id:165,
                                value:5
                            }
                        ]
                    },
                    {
                        id:17,
                        title:'非常不喜欢加班',
                        option:[
                            {
                                id:171,
                                value:1
                            },
                            {
                                id:172,
                                value:2
                            },
                            {
                                id:173,
                                value:3
                            },
                            {
                                id:174,
                                value:4
                            },
                            {
                                id:175,
                                value:5
                            }
                        ]
                    },
                    {
                        id:18,
                        title:'非常满意薪酬',
                        option:[
                            {
                                id:181,
                                value:1
                            },
                            {
                                id:182,
                                value:2
                            },
                            {
                                id:183,
                                value:3
                            },
                            {
                                id:184,
                                value:4
                            },
                            {
                                id:185,
                                value:5
                            }
                        ]
                    },
                    {
                        id:19,
                        title:'非常满意公司环境',
                        option:[
                            {
                                id:191,
                                value:1
                            },
                            {
                                id:192,
                                value:2
                            },
                            {
                                id:193,
                                value:3
                            },
                            {
                                id:194,
                                value:4
                            },
                            {
                                id:195,
                                value:5
                            }
                        ]
                    },
                    {
                        id:20,
                        title:'非常不喜欢公司氛围',
                        option:[
                            {
                                id:201,
                                value:1
                            },
                            {
                                id:202,
                                value:2
                            },
                            {
                                id:203,
                                value:3
                            },
                            {
                                id:204,
                                value:4
                            },
                            {
                                id:205,
                                value:5
                            }
                        ]
                    }
                ]
            },
            {
                departmentsid:3,
                departmentstitle:'部门一',
                questions:[
                    {
                        id:11,
                        title:'非常喜欢休息',
                        option:[
                            {
                                id:111,
                                value:1
                            },
                            {
                                id:112,
                                value:2
                            },
                            {
                                id:113,
                                value:3
                            },
                            {
                                id:114,
                                value:4
                            },
                            {
                                id:115,
                                value:5
                            }
                        ]
                    },
                    {
                        id:12,
                        title:'非常不喜欢工作',
                        option:[
                            {
                                id:121,
                                value:1
                            },
                            {
                                id:122,
                                value:2
                            },
                            {
                                id:123,
                                value:3
                            },
                            {
                                id:124,
                                value:4
                            },
                            {
                                id:125,
                                value:5
                            }
                        ]
                    },
                    {
                        id:13,
                        title:'非常满意工作',
                        option:[
                            {
                                id:131,
                                value:1
                            },
                            {
                                id:132,
                                value:2
                            },
                            {
                                id:133,
                                value:3
                            },
                            {
                                id:134,
                                value:4
                            },
                            {
                                id:135,
                                value:5
                            }
                        ]
                    },
                    {
                        id:14,
                        title:'非常想加班',
                        option:[
                            {
                                id:141,
                                value:1
                            },
                            {
                                id:142,
                                value:2
                            },
                            {
                                id:143,
                                value:3
                            },
                            {
                                id:144,
                                value:4
                            },
                            {
                                id:145,
                                value:5
                            }
                        ]
                    },
                    {
                        id:15,
                        title:'热爱公司文化',
                        option:[
                            {
                                id:151,
                                value:1
                            },
                            {
                                id:152,
                                value:2
                            },
                            {
                                id:153,
                                value:3
                            },
                            {
                                id:154,
                                value:4
                            },
                            {
                                id:155,
                                value:5
                            }
                        ]
                    },
                    {
                        id:16,
                        title:'热爱自己的工作',
                        option:[
                            {
                                id:161,
                                value:1
                            },
                            {
                                id:162,
                                value:2
                            },
                            {
                                id:163,
                                value:3
                            },
                            {
                                id:164,
                                value:4
                            },
                            {
                                id:165,
                                value:5
                            }
                        ]
                    },
                    {
                        id:17,
                        title:'非常不喜欢加班',
                        option:[
                            {
                                id:171,
                                value:1
                            },
                            {
                                id:172,
                                value:2
                            },
                            {
                                id:173,
                                value:3
                            },
                            {
                                id:174,
                                value:4
                            },
                            {
                                id:175,
                                value:5
                            }
                        ]
                    },
                    {
                        id:18,
                        title:'非常满意薪酬',
                        option:[
                            {
                                id:181,
                                value:1
                            },
                            {
                                id:182,
                                value:2
                            },
                            {
                                id:183,
                                value:3
                            },
                            {
                                id:184,
                                value:4
                            },
                            {
                                id:185,
                                value:5
                            }
                        ]
                    },
                    {
                        id:19,
                        title:'非常满意公司环境',
                        option:[
                            {
                                id:191,
                                value:1
                            },
                            {
                                id:192,
                                value:2
                            },
                            {
                                id:193,
                                value:3
                            },
                            {
                                id:194,
                                value:4
                            },
                            {
                                id:195,
                                value:5
                            }
                        ]
                    },
                    {
                        id:20,
                        title:'非常不喜欢公司氛围',
                        option:[
                            {
                                id:201,
                                value:1
                            },
                            {
                                id:202,
                                value:2
                            },
                            {
                                id:203,
                                value:3
                            },
                            {
                                id:204,
                                value:4
                            },
                            {
                                id:205,
                                value:5
                            }
                        ]
                    }
                ]
            },
            {
                departmentsid:4,
                departmentstitle:'部门一',
                questions:[
                    {
                        id:11,
                        title:'非常喜欢休息',
                        option:[
                            {
                                id:111,
                                value:1
                            },
                            {
                                id:112,
                                value:2
                            },
                            {
                                id:113,
                                value:3
                            },
                            {
                                id:114,
                                value:4
                            },
                            {
                                id:115,
                                value:5
                            }
                        ]
                    },
                    {
                        id:12,
                        title:'非常不喜欢工作',
                        option:[
                            {
                                id:121,
                                value:1
                            },
                            {
                                id:122,
                                value:2
                            },
                            {
                                id:123,
                                value:3
                            },
                            {
                                id:124,
                                value:4
                            },
                            {
                                id:125,
                                value:5
                            }
                        ]
                    },
                    {
                        id:13,
                        title:'非常满意工作',
                        option:[
                            {
                                id:131,
                                value:1
                            },
                            {
                                id:132,
                                value:2
                            },
                            {
                                id:133,
                                value:3
                            },
                            {
                                id:134,
                                value:4
                            },
                            {
                                id:135,
                                value:5
                            }
                        ]
                    },
                    {
                        id:14,
                        title:'非常想加班',
                        option:[
                            {
                                id:141,
                                value:1
                            },
                            {
                                id:142,
                                value:2
                            },
                            {
                                id:143,
                                value:3
                            },
                            {
                                id:144,
                                value:4
                            },
                            {
                                id:145,
                                value:5
                            }
                        ]
                    },
                    {
                        id:15,
                        title:'热爱公司文化',
                        option:[
                            {
                                id:151,
                                value:1
                            },
                            {
                                id:152,
                                value:2
                            },
                            {
                                id:153,
                                value:3
                            },
                            {
                                id:154,
                                value:4
                            },
                            {
                                id:155,
                                value:5
                            }
                        ]
                    },
                    {
                        id:16,
                        title:'热爱自己的工作',
                        option:[
                            {
                                id:161,
                                value:1
                            },
                            {
                                id:162,
                                value:2
                            },
                            {
                                id:163,
                                value:3
                            },
                            {
                                id:164,
                                value:4
                            },
                            {
                                id:165,
                                value:5
                            }
                        ]
                    },
                    {
                        id:17,
                        title:'非常不喜欢加班',
                        option:[
                            {
                                id:171,
                                value:1
                            },
                            {
                                id:172,
                                value:2
                            },
                            {
                                id:173,
                                value:3
                            },
                            {
                                id:174,
                                value:4
                            },
                            {
                                id:175,
                                value:5
                            }
                        ]
                    },
                    {
                        id:18,
                        title:'非常满意薪酬',
                        option:[
                            {
                                id:181,
                                value:1
                            },
                            {
                                id:182,
                                value:2
                            },
                            {
                                id:183,
                                value:3
                            },
                            {
                                id:184,
                                value:4
                            },
                            {
                                id:185,
                                value:5
                            }
                        ]
                    },
                    {
                        id:19,
                        title:'非常满意公司环境',
                        option:[
                            {
                                id:191,
                                value:1
                            },
                            {
                                id:192,
                                value:2
                            },
                            {
                                id:193,
                                value:3
                            },
                            {
                                id:194,
                                value:4
                            },
                            {
                                id:195,
                                value:5
                            }
                        ]
                    },
                    {
                        id:20,
                        title:'非常不喜欢公司氛围',
                        option:[
                            {
                                id:201,
                                value:1
                            },
                            {
                                id:202,
                                value:2
                            },
                            {
                                id:203,
                                value:3
                            },
                            {
                                id:204,
                                value:4
                            },
                            {
                                id:205,
                                value:5
                            }
                        ]
                    }
                ]
            }
        ]
    }
]