var dataList=[
    {
        checkoption:ko.observableArray([]),
        id:1,
        questionname:'我对公司未来的发展前景有信心',
        questiontype:0,
        option:[
            {
                id:11,
                optionname:'强烈不同意'
            },
            {
                id:12,
                optionname:'不同意'
            },
            {
                id:13,
                optionname:'基本不同意'
            },
            {
                id:14,
                optionname:'基本同意'
            },
            {
                id:15,
                optionname:'强烈同意'
            }
        ]
    },
    {
        checkoption:ko.observableArray([]),
        id:2,
        questionname:'我对公司未来的发展前景有信心',
        questiontype:0,
        option:[
            {
                id:21,
                optionname:'强烈不同意'
            },
            {
                id:22,
                optionname:'不同意'
            },
            {
                id:23,
                optionname:'基本不同意'
            },
            {
                id:24,
                optionname:'基本同意'
            },
            {
                id:25,
                optionname:'强烈同意'
            }
        ]
    },
    {
        checkoption:ko.observableArray([]),
        id:3,
        questionname:'在公司，创新的行为受到表彰和奖励。',
        questiontype:1,
        option:[
            {
                id:31,
                value:1,
            },
            {
                id:32,
                value:2
            },
            {
                id:33,
                value:3
            },
            {
                id:34,
                value:4
            },
            {
                id:35,
                value:5
            }
        ],
        questiontitle:[
            {
                id:311,
                title:'非常喜欢休息'
            },
            {
                id:312,
                title:'非常不喜欢工作'
            },
            {
                id:313,
                title:'非常满意工作'
            },
            {
                id:314,
                title:'非常想加班'
            },
            {
                id:315,
                title:'热爱公司文化'
            },
            {
                id:316,
                title:'热爱自己的工作'
            },
            {
                id:317,
                title:'非常不喜欢加班'
            },
            {
                id:318,
                title:'非常满意薪酬'
            },
            {
                id:319,
                title:'非常满意公司环境'
            },
            {
                id:320,
                title:'非常不喜欢公司氛围'
            },
            {
                id:321,
                title:'非常不喜欢公司氛围'
            },
            {
                id:322,
                title:'非常不喜欢公司氛围'
            },
        ]

    }
]