//矩阵题测试数据
var Data = {
    id:3,
    questionname:'在公司，创新的行为受到表彰和奖励。',
    questiontype:5,
    leftdepartoption:[
        {
            questionid:1,
            questionname:"游戏开发部"
        },
        {
            questionid:2,
            questionname:"移动开发部"
        },
        {
            questionid:3,
            questionname:"人事管理部"
        },
        {
            questionid:4,
            questionname:"云计算技术部"
        },
        {
            questionid:5,
            questionname:"通讯事业部"
        },
        {
            questionid:6,
            questionname:"无线网络部"
        },
        {
            questionid:7,
            questionname:"人工智能部"
        },
        {
            questionid:8,
            questionname:"销售市场部"
        }
    ],
    topdepartoption:[
        {
            questionid:1,
            questionname:"在公司，创新的行为受到表彰和奖励"
        },
        {
            questionid:2,
            questionname:"公司比竞争对手更快响应用户的反馈，进行产品/服务迭代"
        },
        {
            questionid:3,
            questionname:"我对公司未来的发展前景有信心"
        },
        {
            questionid:4,
            questionname:"总体而言，在这家公司工作我很满意"
        },
        {
            questionid:5,
            questionname:"我很少考虑去其他公司工作"
        },
        {
            questionid:6,
            questionname:"公司具有不断追求创新的动力和意愿"
        },
        {
            questionid:7,
            questionname:"非常不愿意接受外地出差"
        },
        {
            questionid:8,
            questionname:"非常适应公司氛围"
        },
        {
            questionid:9,
            questionname:"我经常付出额外的努力帮助公司取得成功"
        },
        {
            questionid:10,
            questionname:"公司能够应对客户不断变化的需求"
        }
    ],
    selectoption:[
        {
            leftdepartmentid:1,
            leftdepartmentname:"游戏开发部",
            option:[
                {
                    topdepartmentid:1,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:2,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:3,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:4,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:5,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:6,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:7,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:8,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:9,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:10,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                }
            ]
        },
        {
            leftdepartmentid:2,
            leftdepartmentname:"移动开发部",
            option:[
                {
                    topdepartmentid:1,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:2,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:3,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:4,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:5,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:6,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:7,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:8,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:9,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:10,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                }
            ]
        },
        {
            leftdepartmentid:3,
            leftdepartmentname:"人事管理部",
            option:[
                {
                    topdepartmentid:1,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:2,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:3,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:4,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:5,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:6,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:7,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:8,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:9,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:10,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                }
            ]
        },
        {
            leftdepartmentid:4,
            leftdepartmentname:"云计算技术部",
            option:[
                {
                    topdepartmentid:1,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:2,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:3,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:4,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:5,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:6,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:7,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:8,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:9,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:10,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                }
            ]
        },
        {
            leftdepartmentid:5,
            leftdepartmentname:"通讯事业部",
            option:[
                {
                    topdepartmentid:1,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:2,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:3,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:4,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:5,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:6,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:7,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:8,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:9,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:10,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                }
            ]
        },
        {
            leftdepartmentid:6,
            leftdepartmentname:"无线网络部",
            option:[
                {
                    topdepartmentid:1,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:2,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:3,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:4,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:5,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:6,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:7,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:8,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:9,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:10,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                }
            ]
        },
        {
            leftdepartmentid:7,
            leftdepartmentname:"人工智能部",
            option:[
                {
                    topdepartmentid:1,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:2,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:3,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:4,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:5,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:6,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:7,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:8,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:9,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:10,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                }
            ]
        },
        {
            leftdepartmentid:8,
            leftdepartmentname:"销售市场部",
            option:[
                {
                    topdepartmentid:1,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:2,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:3,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:4,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:5,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:6,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:7,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:8,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:9,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                },
                {
                    topdepartmentid:10,
                    option:[
                        {
                            optionid:1,
                            optionname:'强烈不同意'
                        },
                        {
                            optionid:2,
                            optionname:'不同意'
                        },
                        {
                            optionid:3,
                            optionname:'基本不同意'
                        },
                        {
                            optionid:4,
                            optionname:'基本同意'
                        },
                        {
                            optionid:5,
                            optionname:'强烈同意'
                        }
                    ]
                }
            ]
        }
    ]
}

//矩阵对象
var Matrix = {
    Init: function (arr, vm) {                  //初始化绑定矩阵渲染数据
        var _self = this;
        _self.BindingData(arr, vm);
        if (_self.IsHasMatrix()) {
            _self.SetMatrix();
        }
    },
    IsIE: function () {                         //检测是否是IE
        return /msie/i.test(window.navigator.userAgent.toLowerCase());
    },
    IsIE7: function () {                        //检测是否是IE7
        return /msie 7\.0/i.test(window.navigator.userAgent.toLowerCase());
    },
    IsIE8: function () {                        //检测是否是IE8
        return /msie 8\.0/i.test(window.navigator.userAgent.toLowerCase());
    },
    IsHasMatrix: function (arr) {               //是否有有效的矩阵题
        for (var i = 0; i < arr.length; i++) {
            if (arr[i].questiontype == 5 && arr[i].selectoption !== null && arr[i].selectoption.length > 0) {
                return true;
            }
        }
        return false;
    },
    SetMatrix: function (key,arr) {                 //设置矩阵样式和滚动条样式
        var _self = this;
        setTimeout(function () {
            _self.InitStyle();
            _self.SetScroll($(".right_div2"));
            _self.WindowResize();
            _self.RequiredPageMatrix(key,arr);
        },250)
    },
    RequiredPageMatrix: function (key,arr) {               //矩阵题必填验证处理
        var _self = this;
        if (key === 1) {        //key:0,初次调用，不用验证，key:1,点击下一页或提交操作需要验证
            for (var i = 0; i < arr.length; i++) {

                if (arr[i].questiontype == 5 && arr[i].isrequired && arr[i].selectoption !== undefined && arr[i].selectoption.length > 0) {
                    
                    _self.RequiredMatrix(arr[i]);
                }
            }
        }
        //监听select组件值变动时更新样式
        $("body").on("change", "select", function (e) {
            $(this).css("border", "1px solid #ccc");
        })
    },
    RequiredMatrix:function(obj){                           //单个矩阵题必填验证并处理
        var _self=this;
        var KEY = true;         //true:全部填答,false:没有全部填答
        for (var j = 0; j < obj.selectoption.length; j++) {
            var LineID = obj.selectoption[j].leftdepartmentid;
            for (var k = 0; k < obj.selectoption[j].option.length; k++) {
                if (obj.selectoption[j].option[k].checkoption() === undefined) {
                    KEY = false;
                    var RowID = obj.selectoption[j].option[k].topdepartmentid;
                    $("#" + "Left" + LineID + "Top" + RowID).find("select").css("border", "1px solid #ff4949");
                }
            }
        }

        return KEY;

    },
    InitStyle: function () {                    //初始化重置矩阵样式
        var _self = this;
        _self.SetTableLine1();
        _self.SetTableLine2();
        _self.SetResizeWidth();
    },
    SetResizeWidth: function () {               //窗口变化时重置基本样式
        var _self = this;
        _self.SetRightTable();
    },
    ResizeList: function (arr, vm) {            //数据源变化时重新渲染矩阵
        var _self = this;
        _self.Init(arr, vm);
    },
    BindingData: function (arr, vm) {           //数据绑定
        var _self = this;
        var data = _self.ProcessPageData(arr);
        vm.PageList([]);
        vm.PageList(data);
    },
    ProcessPageData: function (arr) {           //处理一页矩阵数据
        var _self = this;
        for (var i = 0; i < arr.length; i++) {
            if (arr[i].questiontype == 0) {
                arr[i].checkoption = ko.observableArray([]);
            } else if (arr[i].questiontype == 5) {
                _self.ProcessMatrixData(arr[i])
            }
        }
        return arr;
    },
    ProcessMatrixData: function (arr) {        //处理一条矩阵数据
        //手动添加selectcheckox,leftcheckbox字段
        if (!arr.selectcheckbox) {
            arr.selectcheckbox = [];
        }

        if (!arr.leftcheckbox) {
            arr.leftcheckbox = [];
        }
        
        for (var i = 0; i < arr.selectoption.length; i++) {
            arr.leftcheckbox.push({ questionid: arr.selectoption[i].leftdepartmentid, questionname: arr.selectoption[i].leftdepartmentname });
            arr.selectcheckbox.push(arr.selectoption[i].leftdepartmentid);
            for (var j = 0; j < arr.selectoption[i].option.length; j++) {
                arr.selectoption[i].option[j].checkoption = ko.observableArray([]);
            }
        }

        return arr;
    },
    SetTableLine1: function () {               //重置第一行所有table高度一致
        var rightTable1 = $(".right_table1");
        for (var i = 0; i < rightTable1.length; i++) {
            var oHeight = rightTable1.eq(i).height();
            var oLeftTable = rightTable1.eq(i).parents(".right_div").siblings(".left_div").find(".left_table1");
            oLeftTable.css("height", oHeight + 'px');
        }
    },
    SetTableLine2: function () {               //重置第二行table使所有tr高度一致(与业务相关，有三种情况：多行多列，单行多列，单列多行)
        var rightTable2 = $(".right_table2");
        for (var i = 0; i < rightTable2.length; i++) {
            if (rightTable2.eq(i).parents(".right_div").siblings(".left_div").find(".left_table2").find(".left_tr").length > 0) {

                var oRightTr = rightTable2.eq(i).find(".right_tr");
                var oLeftTr = rightTable2.eq(i).parents(".right_div").siblings(".left_div").find(".left_table2").find(".left_tr");
                for (var j = 0; j < oLeftTr.length; j++) {
                    var oHeight = oLeftTr.eq(j).height();
                    oRightTr.eq(j).css("height", oHeight + 'px');
                }
            }
        }
    },
    WindowResize: function () {                 //监听窗口变化调整滚动条位置
        var _self = this;
        window.onresize = function () {
            _self.SetResizeWidth();
        }
    },
    SetOtherStyle: function () {                //动态设置其他样式
        
    },
    SetRightTable: function () {                //动态计算右侧容器宽度使浮动不错位
        var rightDiv = $(".right_div");
        var matrixWidth = $(".matrix").width();
        var oRightTable2 = $(".right_table2");
        for (var i = 0; i < rightDiv.length; i++) {
            if (oRightTable2.eq(i).width() <= (matrixWidth - 68)) {
                rightDiv[i].style.width = (oRightTable2.eq(i).width()) + "px";
            } else {
                if (rightDiv.eq(i).hasClass('right_width')) {
                    rightDiv[i].style.width = matrixWidth + "px";
                } else {
                    rightDiv[i].style.width = (matrixWidth - 68) + "px";
                }
            }
        }
    },
    RegisterScroll: function (el) {                //注册滚动事件使同维table一起滚动
        el.on("scroll", function (e) {
            var right_div2_top = $(this)[0].scrollTop;
            var right_div2_left = $(this)[0].scrollLeft;
            $(this).parent().siblings(".left_div").find(".left_div2")[0].scrollTop = right_div2_top;
            $(this).parent().find(".right_div1")[0].scrollLeft = right_div2_left;
        });

        //移动端子元素滚动时禁止父元素滚动
        el.on("touchmove", function (e) {
            e.preventDefault();
        });
    },
    MatrixHideScrollBar:function(){                //翻页隐藏滚动条
        $(".nicescroll-rails").hide();
    },
    SetScroll: function (el) {                     //动态设置元素自定义滚动条
        var _self = this;
        //首先隐藏滚动条
        _self.MatrixHideScrollBar();
        //然后删除所有已有的滚动条
        $(".nicescroll-rails").remove();
        //再然后设置新的滚动条
        el.niceScroll({
            cursorcolor: "#999", //#CC0071 光标颜色
            cursoropacitymax: 1, //改变不透明度非常光标处于活动状态（scrollabar“可见”状态），范围从1到0
            touchbehavior: false, //使光标拖动滚动像在台式电脑触摸设备
            cursorwidth: "5px", //像素光标的宽度
            cursorborder: "0", // 	游标边框css定义
            cursorborderradius: "5px", //以像素为光标边界半径
            autohidemode: false, //是否隐藏滚动条
            scrollspeed: 4, // 滚动速度
            hwacceleration: true, // 激活硬件加速
            mousescrollstep: 60, // 鼠标滚轮的滚动速度 (像素)
            mousescrollstep: 9 * 8 // 鼠标滚动的滚动速度（像素)
        });

        //让新的滚动条显示
        el.getNiceScroll().show();

        //当窗口改变时重置更新滚动条位置
        el.getNiceScroll().resize();

        //注册矩阵滚动事件,使同维table跟随滚动
        _self.RegisterScroll(el);

    }
}
